import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import RootLayout2 from "./layout2";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "easyreserve",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootLayout2>
          <Header />
          <div className=" pt-[50px] lg:pt-[60px]">{children}</div>
          <Footer />
        </RootLayout2>
      </body>
    </html>
  );
}
